was not using logf variable reference

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -15,7 +15,7 @@ function run_hook() {
 
 function start() {
     logf="${OPENSHIFT_LOG_DIR}/hskt.log"
-    echo "Starting hello socket" >> logf
+    echo "Starting hello socket" >> $logf
 
     ruby hellosocket.rb >> $logf 2>&1 &
 
@@ -24,7 +24,7 @@ function start() {
     if [ $ret -eq 0 ] then
             echo "$npid" > "$OPENSHIFT_HSKT_DIR/hskt.pid"
     else
-            echo "Application '$OPENSHIFT_APP_NAME' failed to start - $ret" 1>&2
+            echo "Application '$OPENSHIFT_APP_NAME' failed to start - $ret" 1>&2 >> $logf
             exit $ret
     fi
 }
